### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by davidjeba** [31Carlton7/elisha#1]
suggestion to create API using cloudflare workers
and use cloudflare edge for database, so as a global app its easier and cost effective to run the app on edge locations

**Comment by 31Carlton7** [comment]
The Bible functionality will be moving 100% offline very soon.

**Comment by davidjeba** [comment]
Offline? via Sqlite or firebase realtime database?

**Comment by 31Carlton7** [comment]
Nope, just 5 simple json files from [bible_databases](https://github.com/scrollmapper/bible_databases), and some references to them in app.
