### ISSUE TITLE
Unable to Run Locally - dependency on UI Package

### ISSUE THREAD

**Issue by gerdums** [31Carlton7/elisha#2]
Hello,

I am unable to run this locally because of the dependency on your UI package (which now leads to a 404, I assume you made the repo private?)

**Comment by 31Carlton7** [comment]
Hi, I am currently in the works of refactoring all the UI elements to be added to the app the normal way rather than accessing it from a package as this makes it easier for devs to read and understand the codebase better.

Note: I made the package private for personal reasons.

**Comment by gerdums** [comment]
@31Carlton7 Any update here, I'd like to get this to run locally if possible, so I don't think this should be closed. As a public repo anyone should be able to get the code to run. It will probably take some time I'm sure as this is a side project, but this issue shouldn't be closed since no one can get the code to build without the UI package

**Comment by xandout** [comment]
@31Carlton7 I'd like to second this request.  If you don't want to make it public, would you consider using a github org and allowing private access?

**Comment by 31Carlton7** [comment]
Hello and sorry for the late reply,

I plan on refactoring the app to not use this package and build the main
parts of the UI into the app the normal way. The app is also due for a UI
refresh very soon.

Sorry for the inconvenience.
